### ISSUE TITLE
EA_Main.addGraph return value

### ISSUE THREAD

**Issue by lucdoebereiner** [EnsembleAsAssemblage/couplers#2]
Perhaps 	EA_Main.addGraph should return the new graph, so we could assign it to a variable and later manipulate it without having to count the index manually. It could also return the index, but now it is quite fragile if graphs are added/removed:

This would allow writing it like this:
`
var syncGraph = EA_Main.addGraph([0, 1], [0]);
syncGraph.addLast(sync);
`
instead of `EA_Main.graph(1).addLast(sync);`

**Comment by elblaus** [comment]
It actually does work like that.

**Comment by elblaus** [comment]
`	addGraph { |inputs, outputs|
		var graph;

		graph = EA_Graph.new(this, inputs, outputs);
		graphs = graphs.add(graph);

		^graph
	}`
